/*
 *     Copyright 2026 Philterd, LLC @ https://www.philterd.ai
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ai.philterd.philter.services.filtering;

import ai.philterd.phileas.PhileasConfiguration;
import ai.philterd.phileas.model.filtering.FilterType;
import ai.philterd.phileas.model.filtering.Span;
import ai.philterd.phileas.model.filtering.TextFilterResult;
import ai.philterd.phileas.policy.Policy;
import ai.philterd.phileas.services.filters.filtering.PlainTextFilterService;
import ai.philterd.philter.audit.AuditEventPublisher;
import java.security.SecureRandom;
import ai.philterd.philter.services.cache.ContextCache;
import ai.philterd.philter.services.context.MongoContextService;
import ai.philterd.philter.services.encryption.EncryptionService;
import ai.philterd.philter.services.policies.PolicyResolver;
import ai.philterd.philter.services.vectors.NoOpVectorService;
import ai.philterd.philter.testutil.AbstractMongoIT;
import com.google.gson.Gson;
import com.privacylogistics.FF3Cipher;
import org.apache.hc.client5.http.classic.HttpClient;
import org.bson.types.ObjectId;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;

/**
 * End-to-end tests for the {@code FPE_ENCRYPT_REPLACE} (format-preserving encryption) strategy through
 * the real Phileas filter engine. They use a real per-user FPE key generated by
 * {@link EncryptionService#generateFpeKey()} and the matching {@link EncryptionService#deriveFpeTweak}
 * tweak — exactly what {@code RedactionService} now injects — so the test also pins that those values
 * are valid FF3-1 inputs in the redaction path (FPE silently falls back to redaction on a bad key/tweak,
 * which is how it was broken before this strategy was exposed).
 *
 * <p>A rule-based filter type (SSN) keeps the engine local and deterministic.
 */
class FpeRedactionIT extends AbstractMongoIT {

    private static final String SSN = "123-45-6789";
    private static final String SSN_DIGITS = "123456789";

    // A real FF3-1 key and its derived tweak, mirroring what RedactionService injects per user.
    private static final String FPE_KEY = EncryptionService.generateFpeKey();
    private static final String FPE_TWEAK = EncryptionService.deriveFpeTweak(FPE_KEY);

    private AuditEventPublisher auditEventPublisher;

    @BeforeEach
    void setUpServices() {
        auditEventPublisher = mock(AuditEventPublisher.class);
    }

    @Test
    void fpeReplacementPreservesFormatAndIsNotTheOriginal() throws Exception {

        final String replacement = replacementOf(redact("Patient SSN " + SSN + " is on file."), FilterType.SSN);

        assertNotEquals(SSN, replacement, "the SSN must be encrypted, not left in place");
        assertTrue(replacement.matches("\\d{3}-\\d{2}-\\d{4}"),
                "format-preserving encryption must keep the SSN shape (got: " + replacement + ")");
    }

    @Test
    void fpeIsDeterministicAcrossSeparateRequests() throws Exception {

        // Two independent requests (fresh services), each rebuilding the policy from the same per-user
        // key+tweak. A stable key+tweak makes FPE deterministic, giving referential integrity without
        // requiring CONTEXT scope.
        final String first = replacementOf(redact("SSN " + SSN + " on the intake form."), FilterType.SSN);
        final String second = replacementOf(redact("Reference " + SSN + " in the chart."), FilterType.SSN);

        assertEquals(first, second, "the same SSN must encrypt to the same value across requests");
    }

    @Test
    void fpeReplacementIsReversibleWithTheKeyAndTweak() throws Exception {

        final String replacement = replacementOf(redact("SSN " + SSN + " on file."), FilterType.SSN);

        // Phileas format-preserving encryption operates on the digits, preserving the punctuation, so
        // decrypting the digits of the replacement must recover the original SSN digits.
        final String cipherDigits = replacement.replaceAll("\\D", "");
        final String recoveredDigits = new FF3Cipher(FPE_KEY, FPE_TWEAK).decrypt(cipherDigits);

        assertEquals(SSN_DIGITS, recoveredDigits, "the FPE output must decrypt back to the original SSN");
    }

    // ---- helpers ---------------------------------------------------------------------------------

    private TextFilterResult redact(final String text) throws Exception {

        // The policy supplies no fpe object, so PolicyResolver injects the managed key+tweak exactly as
        // RedactionService does in production.
        final String policyJson = "{\"identifiers\":{\"ssn\":{\"ssnFilterStrategies\":[{\"strategy\":\"FPE_ENCRYPT_REPLACE\"}]}}}";
        final Policy policy = new PolicyResolver(new Gson(), null).resolve(policyJson, null, FPE_KEY, FPE_TWEAK);

        final Properties properties = new Properties();
        properties.put("incremental.redactions.enabled", "true");
        properties.put("span.disambiguation.enabled", "false");
        final PhileasConfiguration configuration = new PhileasConfiguration(properties);

        final MongoContextService contextService = new MongoContextService(
                mongoClient, new ContextCache(null, 0, null, false), new ObjectId(), "ctx", auditEventPublisher);

        final PlainTextFilterService filterService = new PlainTextFilterService(
                configuration, contextService, new NoOpVectorService(), new SecureRandom(), mock(HttpClient.class));

        return filterService.filter(policy, "ctx", text);
    }

    private static String replacementOf(final TextFilterResult result, final FilterType filterType) {
        final List<Span> spans = result.getExplanation().appliedSpans().stream()
                .filter(span -> span.getFilterType() == filterType)
                .toList();
        assertEquals(1, spans.size(), "expected exactly one " + filterType + " span");
        return spans.get(0).getReplacement();
    }

}
