services:

  ph-eye:
    image: philterd/ph-eye:1.2.1
    ports:
      - "18080:5000"
    networks:
      - philter
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all

  philter:
    depends_on:
      ph-eye:
        condition: service_started
    build:
      context: .
    environment:
      API_REQUESTS_INDEXING_ENABLED: true
    ports:
      - "8080:8080"
    volumes:
      - ./distribution/philter.properties:/opt/philter/philter.properties
      - ./distribution/indexes/:/opt/philter/indexes/
      - ./distribution/policies/:/opt/philter/policies/
    networks:
      - philter

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - philter

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - philter
    command: valkey-server --save 60 1 --loglevel warning

networks:
  philter:
