services:

  philter:
    depends_on:
      ph-eye:
        condition: service_started
      mongodb:
        condition: service_healthy
      opensearch:
        condition: service_healthy
      valkey:
        condition: service_healthy
    build:
      context: .
    environment:
      API_REQUESTS_INDEXING_ENABLED: true
      OPENSEARCH_HOST: opensearch
      OPENSEARCH_PORT: 9200
      OPENSEARCH_SCHEME: http
      #OPENSEARCH_USERNAME:
      #OPENSEARCH_PASSWORD:
      CACHE_HOSTNAME: valkey
      CACHE_PORT: 6379
      #CACHE_PASSWORD:
      CACHE_SSL: false
      MONGODB_CONNECTION_STRING: mongodb://mongodb:27017/philter
    ports:
      - "8080:8080"
    networks:
      - philter

  ph-eye:
    image: philterd/ph-eye:1.2.1
    ports:
      - "18080:5000"
    networks:
      - philter
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: philter
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - philter
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  opensearch:
    image: opensearchproject/opensearch:3.5.0
    environment:
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: "true"
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - philter
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    networks:
      - philter
    command: valkey-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  philter:
